start: "Nice to meet you!\n\nMy name is StockDrop, and I'm your notifier manager. command instruction needs update. Refer to command.md for the most recent info."
help: "command instruction needs update. Refer to command.md for the most recent info. "
list_start: "Please select the type you want to list."
list_choice: "Press for more information."
list_empty: "No information to display."
list_notifier: "notifier info is as follows:"
list_filter: "filter info:"
filter_success: "Filter parameter successfully registered."
filter_failure: "Filter parameter registration failed."
filter_warning: "The parameter is successfully registered, but it may result in unstable operation."
price_error: "price_ceiling should be a non-negative integer."
rest_error: "rest_time should be two positive integers in range [0, 24]."
freq_error: "request_frequency should be a non-negative floating point number."
freq_warning: "the frequency value is higher than the recommended value (0.3)."
refresh_error: "update_interval should be a non-negative integer."
add_error: "notifier can only be added after all required filter parameters are set."
add_success: "notifier successfully added."
add_failure: "notifier registration failed."
rm_error: "rm argument should be one or more valid notifier id."
rm_success: "notifier successfully removed."
rm_failure: "notifier removal failed."
